security:
  jwt:
    secret: "MWM0NzE4MDk2MGQwMWFkNjZiNDQ5ZTJkMTJjYTE2N2M1YTFhY2E3M2UzMzBlMGMzZjU3OGVhMGQwMmQyZGM5OTgyODJlOWIwZGVhMzJkOTUzNTdlMjM4ZDIxMTk0YjgzNmEzNDNlMTBjZTMwMGMyNjgzYTc2ZTlmZjE5MzZkZmM" # Replace with a secure secret
    accessExpiration: 900          # Access token valid for 15 minutes (in seconds)
    refreshExpiration: 259200      # Refresh token valid for 3 days (in seconds)
    rememberMeExpiration: 2592000  # Remember me token valid for 30 days (in seconds)

smtp:
  host: smtp.gmail.com
  port: 587
  username: leminhducqvbn@gmail.com
  password: igis ykhd bkll fbjk
mail:
  smtp:
    auth: true
    starttls:
      enable: true

integration:
  minio:
    access-key: admin
    secret-key: admin@2024
    url: http://localhost:9000
