version: "3.8"

services:
  minio:
    image: bitnami/minio:latest
    container_name: minio-online-course
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin@2024
    ports:
      - '9000:9000'
      - '9001:9001'
    command: minio server /bitnami/minio/data --console-address ":9001"
